<a href="https://colab.research.google.com/github/janairacs/bootcamp_WoMakersCode_Desafio_Python/blob/main/Desafio_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Instalação do pydataset
!pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 13.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pydataset) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->pydataset) (1.16.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (setup.py) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939416 sha256=8df9a2cbafb87280f6c69ebb1c0da1c09d538039df10ca67cebcc6ba32812981
  Stored in directory: /root/.cache/pip/wheels/2b/83/5c/073c3755e8b7704e4677557b2055e61026c1a2342149214c13
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [4]:
 # Importando o pydataset
from pydataset import data

initiated datasets repo at: /root/.pydataset/

In [5]:
# Código do dataset
codigo_dataset = "plantTraits"

In [6]:
#1. Importe o dataset utilizando a seguinte função do pydataset: data(“Código”)

# Importando o dataset utilizando a função data do pydataset
df = data(codigo_dataset)

In [7]:
#2. Imprimir na tela o dataset;

# Imprimindo na tela o dataset as 10 primeiras linhas
df.head (10)

,pdias,longindex,durflow,height,begflow,mycor,vegaer,vegsout,autopoll,insects,...,seashiv,seasver,everalw,everparti,elaio,endozoo,epizoo,aquat,windgl,unsp
Aceca,96.84,0.000000,2,7,5,2.0,0.0,0.0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Aceps,110.72,0.000000,3,8,4,2.0,0.0,0.0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Agrca,0.06,0.666667,3,2,6,2.0,0.0,1.0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Agrst,0.08,0.488889,2,2,7,1.0,2.0,0.0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Ajure,1.48,0.476190,3,2,5,2.0,2.0,0.0,1,3,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Allpe,2.33,0.500000,3,5,4,0.0,0.0,0.0,3,3,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Anaar,0.38,0.904762,3,2,6,2.0,0.0,0.0,3,2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Anene,2.55,0.066667,3,2,3,2.0,0.0,2.0,1,3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Angsy,1.48,0.210526,3,3,7,2.0,0.0,0.0,0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Antod,0.52,0.369565,3,2,4,2.0,0.0,0.0,2,0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [8]:
#3. Informe o tipo de dados retornado pela função data

#Informando o tipo de dados retornado pela função data;
print("\nTipo de dados retornado pela função data:", type(df))

Tipo de dados retornado pela função data: <class 'pandas.core.frame.DataFrame'>

In [9]:
# 4. Informe o número de exemplos (linhas) e características (colunas) do dataset.

# Informando o número de exemplos (linhas) e características (colunas) do dataset
num_linhas, num_colunas = df.shape
#linhas
print("\nNúmero de exemplos (linhas):", num_linhas)

#colunas
print("Número de características (colunas):", num_colunas)

Número de exemplos (linhas): 136
Número de características (colunas): 31

In [10]:
#5. Crie uma função que ao receber um DataFrame retorna o número de linhas e colunas.

# Esta função recebe um DataFrame como entrada e retorna uma tupla contendo o número de linhas e colunas do DataFrame.
def informeLinhas(df):

  # A função shape retorna uma tupla com o número de linhas e colunas do DataFrame.
  return df.shape

# Importando o dataset 'plantTraits'
df = data('plantTraits')

# Chamando a função informeLinhas com o DataFrame df como argumento e imprimindo o resultado.
print(informeLinhas(df))

(136, 31)